name: osumlog
description: The osum logging library by osumpi
homepage: https://github.com/osumpi
repository: https://github.com/osumpi/osumlog
version: 0.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
